### PR TITLE
The new theme: Anatole-Basic

### PR DESCRIPTION
**Pull request by yemaster**
Based on the anatole-plus theme of my hexo blog.[Anatole-Plus on GitHub](https://github.com/yemaster/Anatole-Plus)

Features: Responsive design, brief introduction beautiful, 3-7 column easy to read

Elaborate, hope to pass

Some screenshots

### CODE REVIEW

**Comment by RoderickQiu** [comment]
Seems to be good. But it's normal that the merge work isn't done before October. Or it will be rejected.

But after all it's good. Good luck.

**Comment by moesoha** [comment]
The theme looks pretty to me but still waiting for other's opinion.
Requested changes are all about code styles which is also a merging prerequisite.

**Comment by yemaster** [comment]
> The theme looks pretty to me but still waiting for other's opinion.
> Requested changes are all about code styles which is also a merging prerequisite.

I have modified the code style and indentation according to your instructions (I wonder if there are any omissions), and I have also modified some styles. If there are any shortcomings, I hope you can point them out, and I will correct them carefully

**Comment by laosb** [comment]
@yemaster

As far as I can tell, you still didn't move some style tags to css files or remove unused code blocks according to the requested changes. Check them out. Easily can be seen on this page.

**Comment by yemaster** [comment]
I carefully reviewed my code, and carefully compared the problems you pointed out to me, and finally completed the modification. If still have any questions, I will fix.

> @yemaster
> 
> As far as I can tell, you still didn't move some style tags to css files or remove unused code blocks according to the requested changes. Check them out. Easily can be seen on this page.

I carefully reviewed my code, and carefully compared the problems you pointed out to me, and finally completed the modification. If still have any questions, I will fix.

**Comment by lin714093880** [comment]
你这css里定义了好多没用到的东西，哪抄的啊

**Comment by yemaster** [comment]
用了许多其他开原的css

**Comment by lin714093880** [comment]
那你要么package.json里引用，要么把用不着的清理干净再重新pr

**Comment by Bambusaceae** [comment]
@yemaster 直接yarn add然后在common.js里引用就好了......犯不着复制粘贴......

**Pull request closed without merging**
